apiVersion: v1
kind: Service
metadata:
  name: restaurant-management
spec:
  type: LoadBalancer
  selector:
    app: restaurant-management
  ports:
  - protocol: TCP
    port: 30001
    targetPort: 5004