apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: order-management-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-management
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80